minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - tailwind-merge@3.7.0

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

shellEmulator: true

allowBuilds:
  vue-demi: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - unrs-resolver
  - vue-demi
